---
title: "Simulation Models of Cultural Evolution in R"
author: "Alex Mesoudi"
output: pdf_document
---

# Table of parameters for Models 1-10

+------------+-----------------------------------------------------------------------------+------------------------+
| Parameter  | Definition                                                                  | Model first introduced |
+============+=============================================================================+========================+
| $N$        | Number of agents in the population.                                         | 1                      |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $t_{max}$  | Maximum number of timesteps or generations.                                 | 1                      |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $r_{max}$  | Maximum number of independent simulation runs.                              | 1                      |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $p$        | Frequency of trait $A$.                                                     | 1                      |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $p_0$      | Starting value of $p$.                                                      | 1                      |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $\mu$      | Probability of unbiased cultural mutation. Specifically, the                | 2                      |
|            |                                                                             |                        |
|            | probability of trait $A$ mutating into trait $B$, or trait $B$              |                        |
|            |                                                                             |                        |
|            | mutating into trait $A$.                                                    |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $\mu_b$    | Probability of biased cultural mutation. Specifically, the                  | 2                      |
|            |                                                                             |                        |
|            | probability of trait $B$ mutating into trait $A$.                           |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $s$        | Strength of biased transmission / cultural selection.                       | 3                      |
|            |                                                                             |                        |
|            | Specifically, in Model 3 (direct bias) the probability                      |                        |
|            |                                                                             |                        |
|            | of switching to a more favourable trait upon encountering                   |                        |
|            |                                                                             |                        |
|            | another agent with that trait, or in Model 4 (indirect bias)                |                        |
|            |                                                                             |                        |
|            | the payoff advantage to trait $A$ relative to trait $B$.                    |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $q$        | Frequency of a second trait in a two-trait model (trait $X$                 | 4                      |
|            |                                                                             |                        |
|            | in Model 4), or the frequency of trait $A$ in a second                      |                        |
|            |                                                                             |                        |
|            | sub-population or group (Model 7).                                          |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $q_0$      | Starting value of $q$.                                                      | 4                      |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $L$        | Probability in two-trait models that the two traits are linked.             | 4                      |
|            |                                                                             |                        |
|            | Specifically, the probability that, if trait 1 is $A$, then trait 2 is $X$. |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $D$        | Strength of conformity. Specifically, the increased probability             | 5                      |
|            |                                                                             |                        |
|            | of adopting a majority trait, relative to unbiased transmission.            |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $s_v$      | Strength of biased transmission / cultural selection under                  | 6                      |
|            |                                                                             |                        |
|            | vertical cultural transmission. Specifically, the increased probability     |                        |
|            |                                                                             |                        |
|            | of adopting a favoured trait, relative to unbiased transmission,            |                        |
|            |                                                                             |                        |
|            | when only one parent holds that favoured trait.                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $s_h$      | Strength of biased transmission / cultural selection under                  | 6                      |
|            |                                                                             |                        |
|            | horizontal cultural transmission. Specifically, the probability of          |                        |
|            |                                                                             |                        |
|            | switching to a more favourable trait upon encountering at least             |                        |
|            |                                                                             |                        |
|            | one of $n$ demonstrators with that trait.                                   |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $a$        | Probability of assortative mating under vertical cultural                   | 6                      |
|            |                                                                             |                        |
|            | transmission, such that both parents have identical                         |                        |
|            |                                                                             |                        |
|            | cultural traits.                                                            |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $n$        | Number of demonstrators from whom an agent learns under                     | 6                      |
|            |                                                                             |                        |
|            | horizontal transmission (Model 6) or blending inheritance                   |                        |
|            |                                                                             |                        |
|            | (Model 8).                                                                  |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $m$        | Strength of migration. Specifically, the probability that each              | 7                      |
|            |                                                                             |                        |
|            | agent migrates to a randomly chosen sub-population.                         |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $e$        | Error in copying the traits of $n$ demonstrators under blending             | 8                      |
|            |                                                                             |                        |
|            | inheritance. Specifically, the variance of the normal distribution          |                        |
|            |                                                                             |                        |
|            | with mean of the demonstrator trait value, from which the                   |                        |
|            |                                                                             |                        |
|            | copied trait value is drawn.                                                |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $\alpha$   | Copying error in the 'Tasmanian' model of cultural gain/loss.               | 9                      |
|            |                                                                             |                        |
|            | Specifically, the amount by which the mode of a gumbel                      |                        |
|            |                                                                             |                        |
|            | distribution is reduced relative to the highest skill level in              |                        |
|            |                                                                             |                        |
|            | the previous generation.                                                    |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $\beta$    | Inferential guesses or experimentation in the 'Tasmanian'                   | 9                      |
|            |                                                                             |                        |
|            | model of cultural gain/loss. Specifically, the dispersion of                |                        |
|            |                                                                             |                        |
|            | the gumbel distribution from which the new skill level is drawn.            |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $z_i$      | Culturally transmitted skill level of the $i$th agent in the 'Tasmanian'    | 9                      |
|            |                                                                             |                        |
|            | model of cultural gain/loss.                                                |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $\bar{z}$  | Mean culturally transmitted skill level across all agents of one            | 9                      |
|            |                                                                             |                        |
|            | generation in the 'Tasmanian' model of cultural gain/loss.                  |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $g$        | The number of cultural features in Axelrod's model of polarization,         | 10                     |
|            |                                                                             |                        |
|            | with each feature taking one of ten possible trait values.                  |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
| $N_{side}$ | The number of agents along one side of a square grid in Axelrod's           | 10                     |
|            |                                                                             |                        |
|            | model of polarization, giving ${N_{side}}^2$ agents in total.               |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
|            |                                                                             |                        |
+------------+-----------------------------------------------------------------------------+------------------------+
